var YahrzeitList = '{ "Yahrzeits": [' +
'{"ID":"100000","Name":"Rabbi Shlomo Itzhaki","HName":"רבי שלמה יצחקי, רש","EDate":"1105-07-13","HDate":"29 Tamuz, 4865","MournBy":"Everyone","Relationship":"Students","Pic01":"rashi01.jpg","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":"Enough can never be said."},' +
'{"ID":"100001","Name":"Moses Maimonides","HName":"מֹשֶׁה בֶּן־מַיְמוּן","EDate":"1204-12-12","HDate":"20 Tevet, 4965","MournBy":"Everyone","Relationship":"Students","Pic01":"rambam01.jpg","Pic02":"rambam02.jpg","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":"Enough can never be said."},' +
'{"ID":"100002","Name":"Israel ben Eliezer","HName":"בעל שם טוב‬","EDate":"1760-05-22","HDate":"6 Sivan, 5520","MournBy":"Hasidim Everywhere","Relationship":"Students","Pic01":"1523064977-baal-shem-tov.jpg","Pic02":"","PDF01":"Besht_Siddur.jpg","PDF02":"Besht_Shul1_Medzhibozh.jpg","PDF03":"BaalShemMatzeivoh.jpg","PDF04":"","PDF05":"","PayLevel":"4","Comments01":"He started everything!"},' +
'{"ID":"100004","Name":"Rav Moshe Schick","HName":"Maharam Schick","EDate":"","HDate":"1 Shevat","MournBy":"Hasidim Everywhere","Relationship":"Students","Pic01":"","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":"(1807-1879) He learned under the Chasam Sofer from 1821-1827 in Pressburg. He was Rov in Verginin 1838, and then Chust in 1861. In Chust he founded a Yeshiva that numbered hundreds of students. He fought against the Reform movement and called upon the Orthodox to organize separate communities, which came to fruition in 1868. His responsa, “Shut Maharam Shik” contains 1000 responsa; he wrote seferim of drashot and chiddushim on the Torah as well."},' +
'{"ID":"100005","Name":"Rav Yoshua Leib Diskin","HName":"Rav Yoshua Leib Diskin","EDate":"","HDate":"29 Tevet","MournBy":"","Relationship":"Students","Pic01":"RDiskin01.jpg","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"3","Comments01":"Born: Grodna, in Bellerus, 1819 and died in Jerusalem (5658/1898). The Rov of Brisk, son of Reb Binyamin Diskin, rov of Volkovisk. He was a Posek and great leader in his generation, known today as the Maharal Diskin. He became rov in various cities such as Lomza, Mezritch, Kovno, Shklov, and finally in Brisk, and became known as the Rav from Brisk in Israel. He moved to Eretz Yisroel after Yom Kippur in 1876, and settled in Jerusalem. He was a great scholar known for his cleverness and fear of Heaven. Many people would flock to him for advice and blessing, especially for medical advice. He founded the Diskin Orphanage, and Yeshivat Ohel Moshe, where he taught."},' +
'{"ID":"100006","Name":"Rav Nathan Marcus Adler","HName":"Rav Nathan Marcus Adler","EDate":"1973-01-01","HDate":"29 Tevet","MournBy":"","Relationship":"Students","Pic01":"RAdler01.jpg","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":""},' +
'{"ID":"100007","Name":"Rav Moshe Yechiel Halevi from Ozrov","HName":"‬","EDate":"","HDate":"1 Shevat, 5731","MournBy":"","Relationship":"","Pic01":"","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"3","Comments01":"The author of Aish Dos and Beer Moshe."},' +
'{"ID":"100008","Name":"Rav Ben Shimon Mantzur","HName":"Rav Ben Shimon Mantzur","EDate":"1998-01-01","HDate":"2 Shevat, 5758","MournBy":"","Relationship":"Students","Pic01":"","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":"One of the Elder Kabbalists of Jerusalem."},' +
'{"ID":"100009","Name":"Rav Yosef Mashash","HName":"Rav Yosef Mashash","EDate":"1998-01-01","HDate":"2 Shevat, 5758","MournBy":"","Relationship":"Students","Pic01":"","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":"One of the Elder Kabbalists of Jerusalem."},' +
'{"ID":"100010","Name":"Rav Simcha Bunim Kalisch of Otvosk","HName":"Rav Simcha Bunim Kalisch of Otvosk","EDate":"1907-01-01","HDate":"2 Shevat, 5667","MournBy":"","Relationship":"Students","Pic01":"","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":"The son of Reb Menachem Mendel of Vorka."},' +
'{"ID":"100012","Name":"Asher ben Yaakov Avinu","HName":"‬Asher ben Yaakov Avinu","EDate":"","HDate":"2 Shevat, 5731","MournBy":"","Relationship":"","Pic01":"","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"3","Comments01":"The eighth son of our Patriarch Yaakov, one of the Twelve Tribes, he was the son of Zilpah, the maid-servant of Leah. Born in Charan in 1567 BCE, he lived 123 years"},' +
'{"ID":"100013","Name":"Rebbe Nachman of Breslov","HName":"רבי נחמן ברעסלאווער","EDate":"1810-10-16","HDate":"18 Tishrei, 5571","MournBy":"","Relationship":"","Pic01":"RNachman.jpg","Pic02":"","PDF01":"TzionRNachman.jpg","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"3","Comments01":"Rebbe Nachman, a great-grandson of the Baal Shem Tov, revived the Hasidic movement by combining the esoteric secrets of Judaism (the Kabbalah) with in-depth Torah scholarship. He attracted thousands of followers during his lifetime, and his influence continues today through many Hasidic movements such as Breslov Hasidism. Rebbe Nachmans religious philosophy revolved around closeness to God and speaking to God in normal conversation  as you would with a best friend.  The concept of hitbodedut is central to his thinking"},' +
'{"ID":"100014","Name":"Shneur Zalman of Liadi","HName":"שניאור זלמן מליאדי","EDate":"1982-01-19","HDate":"24 Tevet, 5742","MournBy":"","Relationship":"","Pic01":"Schneur_Zalman_of_Liadi.jpg","Pic02":"Tanya.jpg","PDF01":"AlterWriting.jpg","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"3","Comments01":"Baal haTanya"},' +
'{"ID":"100015","Name":"Elimelech Weisblum of Lizhensk","HName":"הצדיק הקדוש רבי רבי אלימלך מליזענסק, בעל נועם אלימלך","EDate":"1787-03-11","HDate":"21 Adar, 5547","MournBy":"","Relationship":"","Pic01":"ElimelechMatzevah.PNG","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"3","Comments01":"On one occasion Rabbi Elimelech and Reb Zushya were staying at an inn. Each night non-Jewish peasants would enter their room and jestingly beat the one who lay nearest the fireside, Reb Zushya. One night, Rabbi Elimelech offered to change places with his brother so that he could take the beatings instead. Suggesting that Reb Zushya had suffered enough of this  Divine admonishment  the agreement was made and Rabbi Elimelech lay next to the fire instead. That night, the common gentiles again entered to begin their jest.  This time, however, one of them said that the one by the fire had taken his fair share of the treatment, and now it would be better to jest with the other one!"},' +
'{"ID":"100016","Name":"Rebbe Reb Zushya of Annapole","HName":"Rebbe Reb Zushya of Annapole","EDate":"1800-01-28","HDate":"2 Shevat, 5560","MournBy":"","Relationship":"","Pic01":"","Pic02":"","PDF01":"Ostropoler01.png","PDF02":"Ostropoler02.png","PDF03":"Ostropoler03.png","PDF04":"Ostropoler04.png","PDF05":"","PayLevel":"3","Comments01":"The Rebbe, Reb Zushya is a major disciple of the Maggid of Mezritch, successor to the Baal Shem Tov. The seemingly unsophisticated but clearly inspired Reb Zusha is one of the best known and most beloved Chassidic personalities. He and his famous brother, Rebbe Elimelech of Lizensk, spent many years wandering in exile, for esoteric reasons."},' +
'{"ID":"100017","Name":"Hershele Ostropoler","HName":"הערשעלע אסטראפאלער","EDate":"1810-03-21","HDate":"15 Adar II, 5570","MournBy":"","Relationship":"","Pic01":"","Pic02":"","PDF01":"","PDF02":"","PDF03":"","PDF04":"","PDF05":"","PayLevel":"3","Comments01":""},' +
'{"ID":"100003","Name":"Rabbi Levi Yitzchak of Berditzhov","HName":"רבי לוי יצחק מברדיטשוב","EDate":"1809-10-05","HDate":"25 Tishrei, 5570","MournBy":"All Chasidim","Relationship":"Students","Pic01":"LeviYitzchak.jpg","Pic02":"","PDF01":"LeviYitzchakMatzevah.jpg","PDF02":"LeviYitzchakMatzevah2.jpg","PDF03":"","PDF04":"","PDF05":"","PayLevel":"4","Comments01":""}]}';
